-- Drop ALL
DROP TRIGGER TR_GCLIENTES_AUTOINCREMENT;
DROP SEQUENCE SQ_CLIENTES_AUTOINCREMENT;

DROP TRIGGER TR_GRESERVAS_AUTOINCREMENT;
DROP SEQUENCE SQ_RESERVAS_AUTOINCREMENT;

DROP TRIGGER TR_GHOTELES_AUTOINCREMENT;
DROP SEQUENCE SQ_HOTELES_AUTOINCREMENT;

-- Creamos el paquete para crear, eliminar, editar un cliente
CREATE OR REPLACE PACKAGE GESTION_CLIENTES
AS
PROCEDURE INSERTAR(ANOMBRES VARCHAR2, ACEDULA VARCHAR2);
FUNCTION ACTUALIZAR(ANOMBRES VARCHAR2, ACEDULA VARCHAR2) RETURN NUMBER;
PROCEDURE ELIMINAR(ACEDULA VARCHAR2);
END;
/

CREATE OR REPLACE PACKAGE BODY GESTION_CLIENTES
AS
    -- Metodo para insertar un nuevo cliente en la tabla clientes.
    PROCEDURE INSERTAR(ANOMBRES VARCHAR2, ACEDULA VARCHAR2) AS
    BEGIN
        INSERT INTO CLIENTES(ID, NOMBRES, CEDULA) VALUES((SELECT MAX(ID)+1 FROM CLIENTES), ANOMBRES, ACEDULA);
        COMMIT;
    END;

    -- Funcion para actualizar nombre de un cliente de la tabla clientes.
    FUNCTION ACTUALIZAR(ANOMBRES VARCHAR2, ACEDULA VARCHAR2) RETURN NUMBER AS
    V NUMBER:=0;
    BEGIN
        UPDATE CLIENTES SET NOMBRES=ANOMBRES WHERE CEDULA=ACEDULA;
        V:=SQL%ROWCOUNT;
        COMMIT;
        RETURN V;
    END;

    -- Metodo para eliminar cliente de la tabla clientes.
    PROCEDURE ELIMINAR(ACEDULA VARCHAR2) AS
    BEGIN
        DELETE CLIENTES WHERE CEDULA=ACEDULA;
        COMMIT;
    END;
END;
/

-- Creamos el paquete para crear, eliminar una reservación
CREATE OR REPLACE PACKAGE GESTION_RESERVAS
AS
PROCEDURE INSERTAR(ACLIENTE NUMBER, AHOTEL NUMBER, AFECHA DATE, AVALOR FLOAT, ATEMPORADA NUMBER);
PROCEDURE ELIMINAR(AID NUMBER);
END;
/

CREATE OR REPLACE PACKAGE BODY GESTION_RESERVAS
AS
    -- Metodo para insertar una nueva reservacion en la tabla reservaciones.
    PROCEDURE INSERTAR(ACLIENTE NUMBER, AHOTEL NUMBER, AFECHA DATE, AVALOR FLOAT, ATEMPORADA NUMBER) AS
    BEGIN
        INSERT INTO RESERVAS(ID, CLIENTE, HOTEL, FECHA, VALOR, TEMPORADA) VALUES((SELECT MAX(ID)+1 FROM RESERVAS),ACLIENTE, AHOTEL, AFECHA, AVALOR, ATEMPORADA);
        COMMIT;
    END;

    -- Metodo para eliminar reserva de la tabla reservas.
    PROCEDURE ELIMINAR(AID NUMBER) AS
    BEGIN
        DELETE RESERVAS WHERE ID=AID;
        COMMIT;
    END;
END;
/


-- Creamos el paqute para crear, eliminar hoteles
CREATE OR REPLACE PACKAGE GESTION_HOTELES
AS
PROCEDURE INSERTAR(ADIRECCION VARCHAR2, ACIUDAD VARCHAR2, APISCINA NUMBER, AJACUZZI NUMBER, ASAUNA NUMBER, AMASAJES NUMBER, ATURCO NUMBER, AJUEGOS NUMBER, APLAYA NUMBER, ABAR NUMBER, ADISCOTECA NUMBER);
FUNCTION ACTUALIZAR(AID NUMBER, ADIRECCION VARCHAR2) RETURN NUMBER;
PROCEDURE ELIMINAR(AID NUMBER);
END;
/

CREATE OR REPLACE PACKAGE BODY GESTION_HOTELES
AS
    -- Metodo para insertar un nuevo hotel en la tabla hoteles.
    PROCEDURE INSERTAR(ADIRECCION VARCHAR2, ACIUDAD VARCHAR2, APISCINA NUMBER, AJACUZZI NUMBER, ASAUNA NUMBER, AMASAJES NUMBER, ATURCO NUMBER, AJUEGOS NUMBER, APLAYA NUMBER, ABAR NUMBER, ADISCOTECA NUMBER) AS
    BEGIN
        INSERT INTO HOTELES(ID, DIRECCION, CIUDAD, PISCINA, JACUZZI, SAUNA, MASAJES, TURCO, JUEGOS, PLAYA, BAR, DISCOTECA) VALUES((SELECT MAX(ID)+1 FROM CLIENTES), ADIRECCION, ACIUDAD, APISCINA, AJACUZZI, ASAUNA, AMASAJES, ATURCO, AJUEGOS, APLAYA, ABAR, ADISCOTECA);
        COMMIT;
    END;

    -- Funcion para actualizar direccion de un hotel de la tabla hoteles.
    FUNCTION ACTUALIZAR(AID NUMBER, ADIRECCION VARCHAR2) RETURN NUMBER AS
    V NUMBER:=0;
    BEGIN
        UPDATE HOTELES SET DIRECCION=ADIRECCION WHERE ID=AID;
        V:=SQL%ROWCOUNT;
        COMMIT;
        RETURN V;
    END;

    -- Metodo para eliminar hotele de la tabla hoteles.
    PROCEDURE ELIMINAR(AID NUMBER) AS
    BEGIN
        DELETE HOTELES WHERE ID=AID;
        COMMIT;
    END;
END;
/

-- Creamos los sinonimos para las diferentes vistas, establecidas en la anterior entrega.
CREATE SYNONYM VHOTELES_V FOR VHOTELES;
CREATE SYNONYM VCLIENTES_V FOR VCLIENTES;
CREATE SYNONYM VTEMPORADAS_V FOR VTEMPORADAS;
CREATE SYNONYM VRESERVAS_V FOR VRESERVAS;

-- Asignamos permisos para acceder a los sinonmimos del Schema Owner
GRANT SELECT ON GET_RESERVAS_POR_HOTEL TO GERENCIA;
GRANT SELECT ON GET_TEMPORADAS_POR_HOTEL TO GERENCIA;
GRANT SELECT, UPDATE, DELETE, INSERT ON VHOTELES TO GERENCIA;
GRANT SELECT, UPDATE, DELETE, INSERT ON VCLIENTES TO GERENCIA;
GRANT SELECT, UPDATE, DELETE, INSERT ON VTEMPORADAS TO GERENCIA;
GRANT SELECT, UPDATE, DELETE, INSERT ON VRESERVAS TO GERENCIA;

GRANT SELECT ON GET_RESERVAS_POR_HOTEL TO RECEPCION;
GRANT SELECT ON VHOTELES TO RECEPCION;
GRANT SELECT, INSERT ON VRESERVAS TO RECEPCION;
GRANT SELECT, INSERT, UPDATE ON VCLIENTES TO RECEPCION;


-- Creamos los sinonimos para los paquetes creados por el Owner
CREATE SYNONYM GESTION_CLIENTES_P FOR GESTION_CLIENTES;
CREATE SYNONYM GESTION_RESERVAS_P FOR GESTION_RESERVAS;
CREATE SYNONYM GESTION_HOTELES_P FOR GESTION_HOTELES;