-- Drop ALL
DROP TRIGGER TR_GCLIENTES_AUTOINCREMENT;
DROP SEQUENCE SQ_CLIENTES_AUTOINCREMENT;

-- Creamos el paquete para crear, eliminar, editar un cliente
CREATE OR REPLACE PACKAGE GESTION_CLIENTES
AS
PROCEDURE INSERTAR_NUEVO_CLIENTE(ANOMBRES VARCHAR2, ACEDULA VARCHAR2);
FUNCTION ACTUALIZAR_NOMBRE_CLIENTE(ANOMBRES VARCHAR2, ACEDULA VARCHAR2) RETURN NUMBER;
PROCEDURE ELIMINAR_CLIENTE(ACEDULA VARCHAR2);
END;
/

CREATE OR REPLACE PACKAGE BODY GESTION_CLIENTES
AS
    -- Metodo para insertar un nuevo cliente en la tabla clientes.
    PROCEDURE INSERTAR_NUEVO_CLIENTE(ANOMBRES VARCHAR2, ACEDULA VARCHAR2) AS
    BEGIN
        INSERT INTO CLIENTES(ID, NOMBRES, CEDULA) VALUES((SELECT MAX(ID)+1 FROM CLIENTES), ANOMBRES, ACEDULA);
        COMMIT;
    END;

    -- Funcion para actualizar nombre de un cliente de la tabla clientes.
    FUNCTION ACTUALIZAR_NOMBRE_CLIENTE(ANOMBRES VARCHAR2, ACEDULA VARCHAR2) RETURN NUMBER AS
    V NUMBER:=0;
    BEGIN
        UPDATE CLIENTES SET NOMBRES=ANOMBRES WHERE CEDULA=ACEDULA;
        V:=SQL%ROWCOUNT;
        COMMIT;
        RETURN V;
    END;

    -- Metodo para eliminar cliente de la tabla clientes.
    PROCEDURE ELIMINAR_CLIENTE(ACEDULA VARCHAR2) AS
    BEGIN
        DELETE CLIENTES WHERE CEDULA=ACEDULA;
        COMMIT;
    END;
END;


-- Creamos el paquete para crear, eliminar una reservación