-- Restablecer Data de Owner
DROP TABLE RESERVAS;
DROP TABLE TEMPORADAS;
DROP TABLE CLIENTES;
DROP TABLE HOTELES;
DROP SEQUENCE SQ_RESERVAS_AUTOINCREMENT;
DROP SEQUENCE SQ_TEMPORADAS_AUTOINCREMENT;
DROP SEQUENCE SQ_CLIENTES_AUTOINCREMENT;
DROP SEQUENCE SQ_HOTELES_AUTOINCREMENT;
DROP VIEW GET_RESERVAS_POR_HOTEL;
DROP VIEW GET_TEMPORADAS_POR_HOTEL;